### PR TITLE
 Add RISC OS support

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by sezero** [comment]
Thanks.

**Comment by psi29a** [comment]
Thanks! :)

**Comment by sezero** [comment]
@ccawley2011: Your change has been causing build failures, because
you used to check the result of `FIND_LIBRARY(M_LIBRARY m)` with
`IF (NOT M_FOUND)` but it should actually be `IF (NOT M_LIBRARY)`.
I fixed that as of commit 12ab79b2436.

Please report back whether the change works for your RiscOS case too.

**Comment by ccawley2011** [comment]
Sorry about that. I can confirm that this still builds fine on RISC OS.

**Pull request merged**
