### PR TITLE
Fix bug in handling of the "source" directive

### PR DESCRIPTION
**Pull request by Ghabry**
Note: The diff without whitespace changes is easier to read: https://github.com/Mindwerks/wildmidi/pull/166/files?w=1

Looks like reading of the pat files fails when dir and source are absolute paths.

When "dir" is different to "source", the recursive call of WM_LoadConfig done by "source" will forget about the directory and look for the instruments in the "source" folder instead.

Arch provides the following /etc/timidity++/timidity.cfg:
```
dir /usr/share/timidity/freepats
source /etc/timidity++/freepats/freepats.cfg
```

This will search for instruments in "/etc/timidity++/freepats/", bad.

How to reproduce (if not on arch click "Download from mirror")
This package: https://www.archlinux.org/packages/extra/x86_64/timidity++/
and https://www.archlinux.org/packages/community/any/timidity-freepats/

And initialize WildMidi with "/etc/timidity++/timidity.cfg".
Before patch: silence
After patch: plays MIDI

### CODE REVIEW

**Comment by sezero** [comment]
This doesn't make sense to me (and can't understand the failure either):
You are changing "source" directive parsing and you are strdup()ing the
'config_dir' as your new_config instead of the arg to the directive i.e.
line_tokens[1].  Without the patch, control should already go to 'else'
case where we do strdup() line_tokens[1] as we should.

**Comment by Ghabry** [comment]
Yeah, to me this also makes no sense, but without that code you get silence o.O.

**Comment by sezero** [comment]
Is the config from that source directive a valid config?
Does parsing it ever fail at any line of it?

**Comment by Ghabry** [comment]
Finally booted Windows and started Visual Studio, hate gdb ;)

By stepping through the code I observe:
"dir" directive sets config_dir to "C:\usr/share/timidity/freepats\"
"source" directive takes last else and sets new_config to "C:\etc/timidity++/freepats/freepats.cfg"
Then "source" calls "WM_LoadConfig" recursive with "new_config" as argument.

There is the problem, the "config_dir" is lost (because it's a local variable) and the new config_dir where it searches the instruments is "C:\etc/timidity++/freepats/" instead.

So the recursive call must keep the config_dir around, could be done through a 2nd internal function (to not break the public API)... lets see.

**Comment by Ghabry** [comment]
Sorry for the initial nonsense patch.
I added a new function "load_config" which does the same as old WM_LoadConfig but accepts a 2nd argument for the "config_path". When the 2nd argument is NULL the old behaviour (config_path is config_file path) happens.
"WM_LoadConfig" calls "load_config" with 2nd argument NULL, so everything happens as before, but "source" will pass a "config_path" as 2nd argument to fix this bug...

**Comment by sezero** [comment]
Thanks!  As far as I can see by eye-balling the old sources, this never would work.
Backporting to wildmidi-0.3 branch too now, will make a new 0.3.12 release later.

**Comment by psi29a** [comment]
Nice detective work on both your parts. Thanks! :D

**Comment by chrisisonwildcode** [comment]
Ok, ya twisted my finger. After I finish off an assessment tonight, I'm going to get looking into the outstanding stuff. 

I also need to look at some of these threads through GitHub, through the emails is looks like Bret has been talking to himself.

Chris

**Comment by chrisisonwildcode** [comment]
Did we yet implement the full fix for this yet where each source file can implement its own dir, as well as search previous dir entries in reverse order for first file match.

It's still on my todo list.

Chris

**Comment by sezero** [comment]
> Did we yet implement the full fix for this yet where each source file can implement
> its own dir, as well as search previous dir entries in reverse order for first file match.

AFAICS, only one search dir is active at a time, after @Ghabry's fix.

**Comment by Ghabry** [comment]
Yepp the code assumes that always only the last search dir is required.

Is there any .cfg file available "in the wild" which uses multiple source statement? Have never seen this before.

**Comment by chrisisonwildcode** [comment]
Yes there is, I have it on my laptop.

Chris

**Pull request merged**
