### PR TITLE
Man pages

### PR DESCRIPTION
**Pull request by psi29a**
Adding new man pages.

### CODE REVIEW

**Comment by psi29a** [comment]
@chrisisonwildcode and @sezero 

I've updated the wildmidi.1 manpage and added more function 3 manpages.

Ugh... this is all the none-fun stuff. ;)

I think there are 2 more to go, conversions.

**Comment by psi29a** [comment]
Last two man-pages created. Suck work, but finished.

Any comments?

**Comment by sezero** [comment]
Made some corrections and clarifications. If you approve, this should be fine IMO.

**Comment by psi29a** [comment]
Thank you for catching these! :)

**Pull request merged**
