### PR TITLE
Update CMake project

### PR DESCRIPTION
**Pull request by winterheart**
Update cmake requirements to 3.1 and rewrite project with features that enhanced in 3.1 version. Added GNUInstallDirs extension for installing target, added exported targets for reuse in external CMake projects.

### CODE REVIEW

**Comment by psi29a** [comment]
@winterheart Thanks for the re-write!
Can you also bump the MacOS version in travis so that we can have some coverage on that side please?
https://travis-ci.org/github/Mindwerks/wildmidi/jobs/740251599

**Comment by winterheart** [comment]
I was intended to switch Github Actions (#216) since there is easy to configuration and maintain. Anyway, Travis configuration updated.

**Comment by psi29a** [comment]
Thanks!

**Comment by sezero** [comment]
I get the following error when trying to cross-compile for windows x64:
```
cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-MinGW64.cmake ..
-- The C compiler identification is GNU 4.5.4
-- Check for working C compiler: /opt/cross_win64/bin/x86_64-w64-mingw32-gcc
-- Check for working C compiler: /opt/cross_win64/bin/x86_64-w64-mingw32-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Setting build type to 'Debug' as none was specified.
-- Build Type: Debug
-- Performing Test HAVE___BUILTIN_EXPECT
-- Performing Test HAVE___BUILTIN_EXPECT - Success
-- Performing Test HAVE_C_INLINE
-- Performing Test HAVE_C_INLINE - Success
-- Performing Test HAVE_C___INLINE__
-- Performing Test HAVE_C___INLINE__ - Success
-- Performing Test HAVE_C___INLINE
-- Performing Test HAVE_C___INLINE - Success
-- Performing Test HAVE_NO_UNDEFINED
-- Performing Test HAVE_NO_UNDEFINED - Success
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
CMake Error at src/CMakeLists.txt:217 (INSTALL):
  INSTALL Library TARGETS given no DESTINATION!


-- Configuring incomplete, errors occurred!
```

**Comment by sezero** [comment]
Well, here is another gem:  This time building for linux with static library enabled:
```
$ cmake -DCMAKE_BUILD_TYPE=Release -DWANT_STATIC=1 .
-- The C compiler identification is GNU 7.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build Type: Release
-- Performing Test HAVE_VISIBILITY_DEFAULT
-- Performing Test HAVE_VISIBILITY_DEFAULT - Success
-- Performing Test HAVE_VISIBILITY_HIDDEN
-- Performing Test HAVE_VISIBILITY_HIDDEN - Success
-- Performing Test HAVE___BUILTIN_EXPECT
-- Performing Test HAVE___BUILTIN_EXPECT - Success
-- Performing Test HAVE_C_INLINE
-- Performing Test HAVE_C_INLINE - Success
-- Performing Test HAVE_C___INLINE__
-- Performing Test HAVE_C___INLINE__ - Success
-- Performing Test HAVE_C___INLINE
-- Performing Test HAVE_C___INLINE - Success
-- Performing Test HAVE_NO_UNDEFINED
-- Performing Test HAVE_NO_UNDEFINED - Success
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Found ALSA: /usr/lib64/libasound.so (found version "1.1.5") 
-- Found OpenAL: /usr/lib64/libopenal.so  
-- Looking for OSS...
-- Looking for include file sys/soundcard.h
-- Looking for include file sys/soundcard.h - found
-- Looking for include file machine/soundcard.h
-- Looking for include file machine/soundcard.h - not found
-- Looking for include file soundcard.h
-- Looking for include file soundcard.h - not found
-- Performing Test OSS_FOUND
-- Performing Test OSS_FOUND - Success
-- Found OSS.
-- M_LIBRARY: /usr/lib64/libm.so
CMake Error at src/CMakeLists.txt:210 (INSTALL):
  INSTALL TARGETS given no ARCHIVE DESTINATION for static library target
  "libwildmidi_static".


-- Configuring incomplete, errors occurred!
```

Either fix this crap or revert these changesets.

**Comment by winterheart** [comment]
@sezero can you please post `cmake --version` and `cmake --trace -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-MinGW64.cmake ..` output.
I tried every available configuration, and don't get same errors.

**Comment by sezero** [comment]
> @sezero can you please post `cmake --version` and `cmake --trace -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-MinGW64.cmake ..` output.

```
$ PATH=$HOME/opt/cmake3.9/bin:$PATH cmake --version
cmake version 3.9.6

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

`$ PATH=$HOME/opt/cmake3.9/bin:$PATH cmake --trace -DCMAKE_TOOLCHAIN_FILE=cmake/Toolchain-MinGW64.cmake . &> ../trace.txt`
Gzip'ed trace.txt attached.
[trace.txt.gz](https://github.com/Mindwerks/wildmidi/files/5474253/trace.txt.gz)

**Comment by sezero** [comment]
In case you need, for the other setup:

```
$ cmake --version
cmake version 3.11.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

`$ $ CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ cmake --trace . &> trace1.txt`
Gzipped trace1.txt attached
[trace1.txt.gz](https://github.com/Mindwerks/wildmidi/files/5474353/trace1.txt.gz)

`$ cmake --trace -DWANT_STATIC=1 . &> trace2.txt`
Gzipped trace2.txt attached
[trace2.txt.gz](https://github.com/Mindwerks/wildmidi/files/5474354/trace2.txt.gz)

**Comment by winterheart** [comment]
Can you please try this branch - https://github.com/winterheart/wildmidi/tree/cmake-2 (commit 4e37c975ef77b18dfd20f23b1cb9a60a3cc45e4d)

**Comment by sezero** [comment]
> Can you please try this branch - https://github.com/winterheart/wildmidi/tree/cmake-2 (commit [4e37c97](https://github.com/Mindwerks/wildmidi/commit/4e37c975ef77b18dfd20f23b1cb9a60a3cc45e4d))

Doesn't make a difference:
```
$ git log|head -5
commit 4e37c975ef77b18dfd20f23b1cb9a60a3cc45e4d
Author: Azamat H. Hackimov <azamat.hackimov@gmail.com>
Date:   Mon Nov 2 13:57:14 2020 +0300

    Specify ARCHIVE and RUNTIME destinations for INSTALL
```

Neither with mingw:
```
-- Check if the system is big endian - little endian
CMake Error at src/CMakeLists.txt:231 (INSTALL):
  INSTALL Library TARGETS given no DESTINATION!


-- Configuring incomplete, errors occurred!
```

Nor with -DWANT_STATIC=1:
```
CMake Error at src/CMakeLists.txt:231 (INSTALL):
  INSTALL TARGETS given no ARCHIVE DESTINATION for static library target
  "libwildmidi_static".


-- Configuring incomplete, errors occurred!
```

**Comment by sezero** [comment]
... And it fails even without specifying any options:
```
$ PATH=$HOME/opt/cmake3.9/bin:$PATH cmake .
[...]
CMake Error at src/CMakeLists.txt:231 (INSTALL):
  INSTALL TARGETS given no LIBRARY DESTINATION for shared library target
  "libwildmidi_dynamic".
```

**Comment by winterheart** [comment]
@sezero please test new changes https://github.com/winterheart/wildmidi/commit/c03732a05aa841e7bab638133a0dc8d1ac915e7f

**Comment by sezero** [comment]
> @sezero please test new changes [winterheart@c03732a](https://github.com/winterheart/wildmidi/commit/c03732a05aa841e7bab638133a0dc8d1ac915e7f)

Seems to work.

**Pull request merged**
