### PR TITLE
initial appveyor commit

### PR DESCRIPTION
**Pull request by psi29a**

### CODE REVIEW

**Comment by psi29a** [comment]
\o/ Wooohoo... one-shot and we now have windows builds! :D

@sezero and @chrisisonwildcode: we're getting there.

It turns out that Appveyor did some serious upgrades on their hardware.

**Comment by psi29a** [comment]
Oh look, we have artifacts too... so we can test the builds. ;)
https://ci.appveyor.com/api/buildjobs/bhma26emj4oe5sg6/artifacts/WildMIDI.zip

**Comment by psi29a** [comment]
Boom, x86 and x32 builds! With artifacts!

**Comment by sezero** [comment]
* The description for WANT_MP_BUILD should read "Build with Multiple Processess"
* What is "OpenMW"?? Should it not be "[lib]WildMIDI"??
* Linking wildmidi player with "/SUBSYSTEM=WINDOWS" seems wrong to me: it is not a gui application, it is a console-only application.
* There is no BUILD_WILDMIDI in our cmakery, but WANT_PLAYER
* There relevant additions for player build/linkage should also be done for statically linked player.

**Pull request merged**
