### PR TITLE
adding polish, refactor and cleanup of cmake files

### PR DESCRIPTION
**Pull request by psi29a**
This is in reference to: https://github.com/Mindwerks/wildmidi/pull/152#issuecomment-238077696

Thanks @sezero for looking at it!  

I've added support for wildmidi-static on MSVC builds.

### CODE REVIEW

**Comment by psi29a** [comment]
You're right about SUBSYSTEM:WINDOWS, we don't have a gui application. Everything should default to console anyway.

**Comment by psi29a** [comment]
This should solve https://github.com/Mindwerks/wildmidi/issues/56

We can now build on WildMIDI and run the newly made executable without messing around with LD_PATH.

**Comment by psi29a** [comment]
Merging in, if there are any issues please let me know. :)

**Comment by sezero** [comment]
@psi29a: Why did we need the openbsd rpath thing of commit 93697ece759acc02415e73ef3233a21c1c271ffe ?

Does Cmake even define `OPENBSD`, BTW ?

**Comment by psi29a** [comment]
rpath in openbsd is tricky stuff, nothing is implied there like on linux or even freebsd. 

I've had the misfortune of having to do this with other projects.

**Comment by sezero** [comment]
OK, keeping it as is.

But considering the cmake check, i.e. `if (OPENBSD)`: does cmake even define `OPENBSD`?

**Comment by psi29a** [comment]
It used to at least?

**Comment by sezero** [comment]
> It used to at least?

Well, I won't bother :)

**Comment by psi29a** [comment]
https://cmake.org/cmake/help/v3.25/variable/BSD.html and https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_BSD.html

Could be that I did some OS magic else where to populate OPENBSD ?

**Comment by sezero** [comment]
> Could be that I did some OS magic else where to populate OPENBSD ?

Most possibly.

At present, I detect OpenBSD like `IF (CMAKE_SYSTEM_NAME MATCHES "kOpenBSD.*|OpenBSD.*")`

**Comment by sezero** [comment]
> > Could be that I did some OS magic else where to populate OPENBSD ?
> 
> Most possibly.
> 
> At present, I detect OpenBSD like `IF (CMAKE_SYSTEM_NAME MATCHES "kOpenBSD.*|OpenBSD.*")`

I changed the OpenBSD check to succeed properly, regardless of `OPENBSD` being defined somewhere.

BTW, I will apply the following: We are using GNUInstallDirs, so it makes sense, yes?
(Notice the removal of duplicate `CMAKE_INSTALL_RPATH` setting.)

**Comment by sezero** [comment]
> BTW, I will apply the following: We are using GNUInstallDirs, so it makes sense, yes? (Notice the removal of duplicate `CMAKE_INSTALL_RPATH` setting.)

[Forgot adding the patch, sigh..]

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 6521727..7bbc2aa 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -95,16 +95,15 @@ IF (SYS_OPENBSD)
     # when building, don't use the install RPATH already
     # (but later on when installing)
     SET(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)
-    SET(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
 
     # add the automatically determined parts of the RPATH
     # which point to directories outside the build tree to the install RPATH
     SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
 
     # the RPATH to be used when installing, but only if it's not a system directory
-    LIST(FIND CMAKE_PLATFORM_IMPLICIT_LINK_DIRECTORIES "${CMAKE_INSTALL_PREFIX}/lib" isSystemDir)
+    LIST(FIND CMAKE_PLATFORM_IMPLICIT_LINK_DIRECTORIES ${CMAKE_INSTALL_FULL_LIBDIR} isSystemDir)
     IF ("${isSystemDir}" STREQUAL "-1")
-        SET(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
+        SET(CMAKE_INSTALL_RPATH ${CMAKE_INSTALL_FULL_LIBDIR})
     ENDIF()
 ENDIF()
 
```

**Comment by sezero** [comment]
> > > Could be that I did some OS magic else where to populate OPENBSD ?
> > 
> > 
> > Most possibly.
> > At present, I detect OpenBSD like `IF (CMAKE_SYSTEM_NAME MATCHES "kOpenBSD.*|OpenBSD.*")`
> 
> I changed the OpenBSD check to succeed properly, regardless of `OPENBSD` being defined somewhere.
> 
> BTW, I will apply the following: We are using GNUInstallDirs, so it makes sense, yes? (Notice the removal of duplicate `CMAKE_INSTALL_RPATH` setting.)

Check with current git master

**Comment by psi29a** [comment]
I'll need to load up openbsd in a VM, I think the original work was done this way too because of a patch from an openbsd dev.

**Comment by sezero** [comment]
Looking at the github actions workflow logs from latest git, it seems to be working:
```
-- Install configuration: "Release"
-- Installing: /home/runner/work/wildmidi/wildmidi/build/out/lib/libWildMidi.a
-- Installing: /home/runner/work/wildmidi/wildmidi/build/out/lib/libWildMidi.so.2.1.0
-- Installing: /home/runner/work/wildmidi/wildmidi/build/out/lib/libWildMidi.so.2
-- Set runtime path of "/home/runner/work/wildmidi/wildmidi/build/out/lib/libWildMidi.so.2.1.0" to "/home/runner/work/wildmidi/wildmidi/build/out/lib"
```
Cmake didn't emit any RPATH setting messages before, e.g. with 3e5ae3096f64744e3a9f75ca3b7c8678463b2c75 and earlier revisions, in the CI logs.

**Pull request merged**
