### PR TITLE
add android ndk make files

### PR DESCRIPTION
**Pull request by loki666**
android/jni/Android.mk is to build the shared library
android/Android.mk is to import the shared library in an application project

### CODE REVIEW

**Comment by psi29a** [comment]
You shouldn't be committing/hard-coding the config.h file, but letting cmake generate for you.

**Comment by loki666** [comment]
I know, unfortunately cmake doesn't cope well with Android NDK
(toolchain)...

**Comment by psi29a** [comment]
Can't you run cmake and have it at least generate the config.h file for you, then run the NDK?

**Comment by loki666** [comment]
Mostly what I did.
I ran cmake for my Linux, then I slightly edited it to disable ALSA driver.
But I probably can keep it untouched since these config are used only by
the player, which I don't use at all.

**Comment by sezero** [comment]
To me, it's OK to have manually generated config.h files for special targets.
The rest is, for android case, pretty much linux.

One thing: Can't remeber whether android runs on bin endian platforms.
If it does, the project / config files need editing for it.

**Comment by loki666** [comment]
the Android.mk only compiles for x86 and arm which are both little endian.
mips and sparc are like non existent on android.

**Comment by psi29a** [comment]
I was concerned about having to modify the config.h file for every release to correct the versions. Is there a way to automate this?

**Comment by loki666** [comment]
it should be possible to execute shell script to retrieve those define config, and add them to the CFLAGS.

something like:
WILDMIDI_VERSION := $(shell ($(LOCAL_PATH)/wildmidi_version.sh))
LOCAL_CFLAGS += -DVERSION=$WILDMIDI_VERSION

how can I retrieve the version?

**Comment by sezero** [comment]
On 8/17/16, Philippe Simons <notifications@github.com> wrote:
> it should be possible to execute shell script to retrieve those define
> config, and add them to the CFLAGS.
>
> something like:
> WILDMIDI_VERSION := $(shell ($(LOCAL_PATH)/wildmidi_version.sh))
> LOCAL_CFLAGS += -DVERSION=$WILDMIDI_VERSION
>
> how can I retrieve the version?

The concern is how do _we_ automate version changing (and _possibly_
other things) ourselves when we change the version number.  It's not
only your android makefile either, the dos and amiga ports I am maintaining
have the same thing.

We can :
- make a small shell script where we touch every file needed, and/or
- make checklist to, erm, check, before we make a release, listing the
thing to be done including such version changes in which files

**Comment by chrisisonwildcode** [comment]
I vote sezero in charge of checklists :p

**Comment by sezero** [comment]
> I vote sezero in charge of checklists :p

Done: commit 27f3ca0

**Comment by sezero** [comment]
In your Android.mk, add:

LOCAL_CFLAGS += -DWILDMIDI_BUILD
LOCAL_CFLAGS += -fvisibility=hidden -DSYM_VISIBILITY

Then this can be accepted IMO.

**Comment by loki666** [comment]
done

**Comment by sezero** [comment]
Merged this.  One question: You name your dso libwildmidi.so, however our official name is (for some historical compatibility reasons) libWildMidi.so (and I'm sure I spelled it wrong..)  Do you want to keep it your way?

**Comment by loki666** [comment]
done in merge request 156

**Pull request merged**
