### PR TITLE
sezero's updates for the wildcode-updates branch

### PR DESCRIPTION
**Pull request by sezero**
sezero's updates for the wildcode-updates branch: pull in the "szo0" branch.

### CODE REVIEW

**Comment by sezero** [comment]
@psi29a, @chrisisonwildcode: if there are no objections, I'd like to merge this tomorrow?

**Comment by psi29a** [comment]
No objects here.

**Comment by chrisisonwildcode** [comment]
I think the only issue I have is you changed an if() do {} while(); to just a while() {} ... I have had issues in the past where some compilers treat while() as do {} while (); so it would go through the while code first time unchecked ...

**Comment by sezero** [comment]
On 1/25/15, chrisisonwildcode <notifications@github.com> wrote:
> I think the only issue I have is you changed an if() do {} while(); to just
> a while() {} ... I have had issues in the past where some compilers treat
> while() as do {} while (); so it would go through the while code first time
> unchecked ...
>

Never heard of that issue before. Which compiler are you talking about?
Besides, our code is, naturally, crawling with while() {} constructs, so I
don't see that my change would be a problem?

**Comment by chrisisonwildcode** [comment]
I forget which compiler, it was back in the days when the lib was tested in a game engine.

I think most of the while loops are safe anyway because of all the checks that happens early on.

Go ahead with what you were going to do, I'll hold off commuting anything more (unless critical) until you're done :)

**Comment by sezero** [comment]
Merged.

**Pull request merged**
